/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardSalesAddRouteImport } from './routes/dashboard/sales/add'
import { Route as DashboardSalesEditSaleIdRouteImport } from './routes/dashboard/sales/edit.$saleId'
import { Route as DashboardProductsItemProductIdRouteImport } from './routes/dashboard/products/item.$productId'
import { Route as DashboardProductsEditProductIdRouteImport } from './routes/dashboard/products/edit.$productId'
import { Route as DashboardMarketsEditMarketIdRouteImport } from './routes/dashboard/markets/edit.$marketId'
import { Route as DashboardEventsItemEventIdRouteImport } from './routes/dashboard/events/item.$eventId'
import { Route as DashboardEventsEditEventIdRouteImport } from './routes/dashboard/events/edit.$eventId'
import { Route as DashboardContactsEditContactIdRouteImport } from './routes/dashboard/contacts/edit.$contactId'
import { Route as DashboardContactsFormItemSubmissionIdRouteImport } from './routes/dashboard/contacts/form/item.$submissionId'

const LoginLazyRouteImport = createFileRoute('/login')()
const IndexLazyRouteImport = createFileRoute('/')()
const DashboardIndexLazyRouteImport = createFileRoute('/dashboard/')()
const DashboardSalesIndexLazyRouteImport =
  createFileRoute('/dashboard/sales/')()
const DashboardProductsIndexLazyRouteImport = createFileRoute(
  '/dashboard/products/',
)()
const DashboardNewsletterIndexLazyRouteImport = createFileRoute(
  '/dashboard/newsletter/',
)()
const DashboardMarketsIndexLazyRouteImport = createFileRoute(
  '/dashboard/markets/',
)()
const DashboardEventsIndexLazyRouteImport =
  createFileRoute('/dashboard/events/')()
const DashboardContactsIndexLazyRouteImport = createFileRoute(
  '/dashboard/contacts/',
)()
const DashboardAnalyticsIndexLazyRouteImport = createFileRoute(
  '/dashboard/analytics/',
)()
const DashboardProductsAddLazyRouteImport = createFileRoute(
  '/dashboard/products/add',
)()
const DashboardMarketsAddLazyRouteImport = createFileRoute(
  '/dashboard/markets/add',
)()
const DashboardEventsAddLazyRouteImport = createFileRoute(
  '/dashboard/events/add',
)()
const DashboardContactsAddLazyRouteImport = createFileRoute(
  '/dashboard/contacts/add',
)()
const DashboardProductsSettingsIndexLazyRouteImport = createFileRoute(
  '/dashboard/products/settings/',
)()
const DashboardContactsFormIndexLazyRouteImport = createFileRoute(
  '/dashboard/contacts/form/',
)()
const DashboardAnalyticsTrafficIndexLazyRouteImport = createFileRoute(
  '/dashboard/analytics/traffic/',
)()

const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const DashboardIndexLazyRoute = DashboardIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardSalesIndexLazyRoute = DashboardSalesIndexLazyRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => DashboardLayoutRoute,
} as any).lazy(() =>
  import('./routes/dashboard/sales/index.lazy').then((d) => d.Route),
)
const DashboardProductsIndexLazyRoute =
  DashboardProductsIndexLazyRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/index.lazy').then((d) => d.Route),
  )
const DashboardNewsletterIndexLazyRoute =
  DashboardNewsletterIndexLazyRouteImport.update({
    id: '/newsletter/',
    path: '/newsletter/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/newsletter/index.lazy').then((d) => d.Route),
  )
const DashboardMarketsIndexLazyRoute =
  DashboardMarketsIndexLazyRouteImport.update({
    id: '/markets/',
    path: '/markets/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/markets/index.lazy').then((d) => d.Route),
  )
const DashboardEventsIndexLazyRoute =
  DashboardEventsIndexLazyRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/events/index.lazy').then((d) => d.Route),
  )
const DashboardContactsIndexLazyRoute =
  DashboardContactsIndexLazyRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contacts/index.lazy').then((d) => d.Route),
  )
const DashboardAnalyticsIndexLazyRoute =
  DashboardAnalyticsIndexLazyRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/analytics/index.lazy').then((d) => d.Route),
  )
const DashboardProductsAddLazyRoute =
  DashboardProductsAddLazyRouteImport.update({
    id: '/products/add',
    path: '/products/add',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/add.lazy').then((d) => d.Route),
  )
const DashboardMarketsAddLazyRoute = DashboardMarketsAddLazyRouteImport.update({
  id: '/markets/add',
  path: '/markets/add',
  getParentRoute: () => DashboardLayoutRoute,
} as any).lazy(() =>
  import('./routes/dashboard/markets/add.lazy').then((d) => d.Route),
)
const DashboardEventsAddLazyRoute = DashboardEventsAddLazyRouteImport.update({
  id: '/events/add',
  path: '/events/add',
  getParentRoute: () => DashboardLayoutRoute,
} as any).lazy(() =>
  import('./routes/dashboard/events/add.lazy').then((d) => d.Route),
)
const DashboardContactsAddLazyRoute =
  DashboardContactsAddLazyRouteImport.update({
    id: '/contacts/add',
    path: '/contacts/add',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contacts/add.lazy').then((d) => d.Route),
  )
const DashboardSalesAddRoute = DashboardSalesAddRouteImport.update({
  id: '/sales/add',
  path: '/sales/add',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardProductsSettingsIndexLazyRoute =
  DashboardProductsSettingsIndexLazyRouteImport.update({
    id: '/products/settings/',
    path: '/products/settings/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/products/settings/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardContactsFormIndexLazyRoute =
  DashboardContactsFormIndexLazyRouteImport.update({
    id: '/contacts/form/',
    path: '/contacts/form/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/contacts/form/index.lazy').then((d) => d.Route),
  )
const DashboardAnalyticsTrafficIndexLazyRoute =
  DashboardAnalyticsTrafficIndexLazyRouteImport.update({
    id: '/analytics/traffic/',
    path: '/analytics/traffic/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/analytics/traffic/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardSalesEditSaleIdRoute =
  DashboardSalesEditSaleIdRouteImport.update({
    id: '/sales/edit/$saleId',
    path: '/sales/edit/$saleId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardProductsItemProductIdRoute =
  DashboardProductsItemProductIdRouteImport.update({
    id: '/products/item/$productId',
    path: '/products/item/$productId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardProductsEditProductIdRoute =
  DashboardProductsEditProductIdRouteImport.update({
    id: '/products/edit/$productId',
    path: '/products/edit/$productId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardMarketsEditMarketIdRoute =
  DashboardMarketsEditMarketIdRouteImport.update({
    id: '/markets/edit/$marketId',
    path: '/markets/edit/$marketId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardEventsItemEventIdRoute =
  DashboardEventsItemEventIdRouteImport.update({
    id: '/events/item/$eventId',
    path: '/events/item/$eventId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardEventsEditEventIdRoute =
  DashboardEventsEditEventIdRouteImport.update({
    id: '/events/edit/$eventId',
    path: '/events/edit/$eventId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardContactsEditContactIdRoute =
  DashboardContactsEditContactIdRouteImport.update({
    id: '/contacts/edit/$contactId',
    path: '/contacts/edit/$contactId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardContactsFormItemSubmissionIdRoute =
  DashboardContactsFormItemSubmissionIdRouteImport.update({
    id: '/contacts/form/item/$submissionId',
    path: '/contacts/form/item/$submissionId',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/sales/add': typeof DashboardSalesAddRoute
  '/dashboard/contacts/add': typeof DashboardContactsAddLazyRoute
  '/dashboard/events/add': typeof DashboardEventsAddLazyRoute
  '/dashboard/markets/add': typeof DashboardMarketsAddLazyRoute
  '/dashboard/products/add': typeof DashboardProductsAddLazyRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexLazyRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexLazyRoute
  '/dashboard/events/': typeof DashboardEventsIndexLazyRoute
  '/dashboard/markets/': typeof DashboardMarketsIndexLazyRoute
  '/dashboard/newsletter/': typeof DashboardNewsletterIndexLazyRoute
  '/dashboard/products/': typeof DashboardProductsIndexLazyRoute
  '/dashboard/sales/': typeof DashboardSalesIndexLazyRoute
  '/dashboard/contacts/edit/$contactId': typeof DashboardContactsEditContactIdRoute
  '/dashboard/events/edit/$eventId': typeof DashboardEventsEditEventIdRoute
  '/dashboard/events/item/$eventId': typeof DashboardEventsItemEventIdRoute
  '/dashboard/markets/edit/$marketId': typeof DashboardMarketsEditMarketIdRoute
  '/dashboard/products/edit/$productId': typeof DashboardProductsEditProductIdRoute
  '/dashboard/products/item/$productId': typeof DashboardProductsItemProductIdRoute
  '/dashboard/sales/edit/$saleId': typeof DashboardSalesEditSaleIdRoute
  '/dashboard/analytics/traffic/': typeof DashboardAnalyticsTrafficIndexLazyRoute
  '/dashboard/contacts/form/': typeof DashboardContactsFormIndexLazyRoute
  '/dashboard/products/settings/': typeof DashboardProductsSettingsIndexLazyRoute
  '/dashboard/contacts/form/item/$submissionId': typeof DashboardContactsFormItemSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/dashboard': typeof DashboardIndexLazyRoute
  '/dashboard/sales/add': typeof DashboardSalesAddRoute
  '/dashboard/contacts/add': typeof DashboardContactsAddLazyRoute
  '/dashboard/events/add': typeof DashboardEventsAddLazyRoute
  '/dashboard/markets/add': typeof DashboardMarketsAddLazyRoute
  '/dashboard/products/add': typeof DashboardProductsAddLazyRoute
  '/dashboard/analytics': typeof DashboardAnalyticsIndexLazyRoute
  '/dashboard/contacts': typeof DashboardContactsIndexLazyRoute
  '/dashboard/events': typeof DashboardEventsIndexLazyRoute
  '/dashboard/markets': typeof DashboardMarketsIndexLazyRoute
  '/dashboard/newsletter': typeof DashboardNewsletterIndexLazyRoute
  '/dashboard/products': typeof DashboardProductsIndexLazyRoute
  '/dashboard/sales': typeof DashboardSalesIndexLazyRoute
  '/dashboard/contacts/edit/$contactId': typeof DashboardContactsEditContactIdRoute
  '/dashboard/events/edit/$eventId': typeof DashboardEventsEditEventIdRoute
  '/dashboard/events/item/$eventId': typeof DashboardEventsItemEventIdRoute
  '/dashboard/markets/edit/$marketId': typeof DashboardMarketsEditMarketIdRoute
  '/dashboard/products/edit/$productId': typeof DashboardProductsEditProductIdRoute
  '/dashboard/products/item/$productId': typeof DashboardProductsItemProductIdRoute
  '/dashboard/sales/edit/$saleId': typeof DashboardSalesEditSaleIdRoute
  '/dashboard/analytics/traffic': typeof DashboardAnalyticsTrafficIndexLazyRoute
  '/dashboard/contacts/form': typeof DashboardContactsFormIndexLazyRoute
  '/dashboard/products/settings': typeof DashboardProductsSettingsIndexLazyRoute
  '/dashboard/contacts/form/item/$submissionId': typeof DashboardContactsFormItemSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/login': typeof LoginLazyRoute
  '/dashboard/': typeof DashboardIndexLazyRoute
  '/dashboard/sales/add': typeof DashboardSalesAddRoute
  '/dashboard/contacts/add': typeof DashboardContactsAddLazyRoute
  '/dashboard/events/add': typeof DashboardEventsAddLazyRoute
  '/dashboard/markets/add': typeof DashboardMarketsAddLazyRoute
  '/dashboard/products/add': typeof DashboardProductsAddLazyRoute
  '/dashboard/analytics/': typeof DashboardAnalyticsIndexLazyRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexLazyRoute
  '/dashboard/events/': typeof DashboardEventsIndexLazyRoute
  '/dashboard/markets/': typeof DashboardMarketsIndexLazyRoute
  '/dashboard/newsletter/': typeof DashboardNewsletterIndexLazyRoute
  '/dashboard/products/': typeof DashboardProductsIndexLazyRoute
  '/dashboard/sales/': typeof DashboardSalesIndexLazyRoute
  '/dashboard/contacts/edit/$contactId': typeof DashboardContactsEditContactIdRoute
  '/dashboard/events/edit/$eventId': typeof DashboardEventsEditEventIdRoute
  '/dashboard/events/item/$eventId': typeof DashboardEventsItemEventIdRoute
  '/dashboard/markets/edit/$marketId': typeof DashboardMarketsEditMarketIdRoute
  '/dashboard/products/edit/$productId': typeof DashboardProductsEditProductIdRoute
  '/dashboard/products/item/$productId': typeof DashboardProductsItemProductIdRoute
  '/dashboard/sales/edit/$saleId': typeof DashboardSalesEditSaleIdRoute
  '/dashboard/analytics/traffic/': typeof DashboardAnalyticsTrafficIndexLazyRoute
  '/dashboard/contacts/form/': typeof DashboardContactsFormIndexLazyRoute
  '/dashboard/products/settings/': typeof DashboardProductsSettingsIndexLazyRoute
  '/dashboard/contacts/form/item/$submissionId': typeof DashboardContactsFormItemSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/sales/add'
    | '/dashboard/contacts/add'
    | '/dashboard/events/add'
    | '/dashboard/markets/add'
    | '/dashboard/products/add'
    | '/dashboard/analytics/'
    | '/dashboard/contacts/'
    | '/dashboard/events/'
    | '/dashboard/markets/'
    | '/dashboard/newsletter/'
    | '/dashboard/products/'
    | '/dashboard/sales/'
    | '/dashboard/contacts/edit/$contactId'
    | '/dashboard/events/edit/$eventId'
    | '/dashboard/events/item/$eventId'
    | '/dashboard/markets/edit/$marketId'
    | '/dashboard/products/edit/$productId'
    | '/dashboard/products/item/$productId'
    | '/dashboard/sales/edit/$saleId'
    | '/dashboard/analytics/traffic/'
    | '/dashboard/contacts/form/'
    | '/dashboard/products/settings/'
    | '/dashboard/contacts/form/item/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/sales/add'
    | '/dashboard/contacts/add'
    | '/dashboard/events/add'
    | '/dashboard/markets/add'
    | '/dashboard/products/add'
    | '/dashboard/analytics'
    | '/dashboard/contacts'
    | '/dashboard/events'
    | '/dashboard/markets'
    | '/dashboard/newsletter'
    | '/dashboard/products'
    | '/dashboard/sales'
    | '/dashboard/contacts/edit/$contactId'
    | '/dashboard/events/edit/$eventId'
    | '/dashboard/events/item/$eventId'
    | '/dashboard/markets/edit/$marketId'
    | '/dashboard/products/edit/$productId'
    | '/dashboard/products/item/$productId'
    | '/dashboard/sales/edit/$saleId'
    | '/dashboard/analytics/traffic'
    | '/dashboard/contacts/form'
    | '/dashboard/products/settings'
    | '/dashboard/contacts/form/item/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/sales/add'
    | '/dashboard/contacts/add'
    | '/dashboard/events/add'
    | '/dashboard/markets/add'
    | '/dashboard/products/add'
    | '/dashboard/analytics/'
    | '/dashboard/contacts/'
    | '/dashboard/events/'
    | '/dashboard/markets/'
    | '/dashboard/newsletter/'
    | '/dashboard/products/'
    | '/dashboard/sales/'
    | '/dashboard/contacts/edit/$contactId'
    | '/dashboard/events/edit/$eventId'
    | '/dashboard/events/item/$eventId'
    | '/dashboard/markets/edit/$marketId'
    | '/dashboard/products/edit/$productId'
    | '/dashboard/products/item/$productId'
    | '/dashboard/sales/edit/$saleId'
    | '/dashboard/analytics/traffic/'
    | '/dashboard/contacts/form/'
    | '/dashboard/products/settings/'
    | '/dashboard/contacts/form/item/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/sales/': {
      id: '/dashboard/sales/'
      path: '/sales'
      fullPath: '/dashboard/sales/'
      preLoaderRoute: typeof DashboardSalesIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products/'
      preLoaderRoute: typeof DashboardProductsIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/newsletter/': {
      id: '/dashboard/newsletter/'
      path: '/newsletter'
      fullPath: '/dashboard/newsletter/'
      preLoaderRoute: typeof DashboardNewsletterIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/markets/': {
      id: '/dashboard/markets/'
      path: '/markets'
      fullPath: '/dashboard/markets/'
      preLoaderRoute: typeof DashboardMarketsIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/contacts/': {
      id: '/dashboard/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts/'
      preLoaderRoute: typeof DashboardContactsIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/analytics/': {
      id: '/dashboard/analytics/'
      path: '/analytics'
      fullPath: '/dashboard/analytics/'
      preLoaderRoute: typeof DashboardAnalyticsIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/products/add': {
      id: '/dashboard/products/add'
      path: '/products/add'
      fullPath: '/dashboard/products/add'
      preLoaderRoute: typeof DashboardProductsAddLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/markets/add': {
      id: '/dashboard/markets/add'
      path: '/markets/add'
      fullPath: '/dashboard/markets/add'
      preLoaderRoute: typeof DashboardMarketsAddLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/events/add': {
      id: '/dashboard/events/add'
      path: '/events/add'
      fullPath: '/dashboard/events/add'
      preLoaderRoute: typeof DashboardEventsAddLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/contacts/add': {
      id: '/dashboard/contacts/add'
      path: '/contacts/add'
      fullPath: '/dashboard/contacts/add'
      preLoaderRoute: typeof DashboardContactsAddLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/sales/add': {
      id: '/dashboard/sales/add'
      path: '/sales/add'
      fullPath: '/dashboard/sales/add'
      preLoaderRoute: typeof DashboardSalesAddRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/products/settings/': {
      id: '/dashboard/products/settings/'
      path: '/products/settings'
      fullPath: '/dashboard/products/settings/'
      preLoaderRoute: typeof DashboardProductsSettingsIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/contacts/form/': {
      id: '/dashboard/contacts/form/'
      path: '/contacts/form'
      fullPath: '/dashboard/contacts/form/'
      preLoaderRoute: typeof DashboardContactsFormIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/analytics/traffic/': {
      id: '/dashboard/analytics/traffic/'
      path: '/analytics/traffic'
      fullPath: '/dashboard/analytics/traffic/'
      preLoaderRoute: typeof DashboardAnalyticsTrafficIndexLazyRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/sales/edit/$saleId': {
      id: '/dashboard/sales/edit/$saleId'
      path: '/sales/edit/$saleId'
      fullPath: '/dashboard/sales/edit/$saleId'
      preLoaderRoute: typeof DashboardSalesEditSaleIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/products/item/$productId': {
      id: '/dashboard/products/item/$productId'
      path: '/products/item/$productId'
      fullPath: '/dashboard/products/item/$productId'
      preLoaderRoute: typeof DashboardProductsItemProductIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/products/edit/$productId': {
      id: '/dashboard/products/edit/$productId'
      path: '/products/edit/$productId'
      fullPath: '/dashboard/products/edit/$productId'
      preLoaderRoute: typeof DashboardProductsEditProductIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/markets/edit/$marketId': {
      id: '/dashboard/markets/edit/$marketId'
      path: '/markets/edit/$marketId'
      fullPath: '/dashboard/markets/edit/$marketId'
      preLoaderRoute: typeof DashboardMarketsEditMarketIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/events/item/$eventId': {
      id: '/dashboard/events/item/$eventId'
      path: '/events/item/$eventId'
      fullPath: '/dashboard/events/item/$eventId'
      preLoaderRoute: typeof DashboardEventsItemEventIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/events/edit/$eventId': {
      id: '/dashboard/events/edit/$eventId'
      path: '/events/edit/$eventId'
      fullPath: '/dashboard/events/edit/$eventId'
      preLoaderRoute: typeof DashboardEventsEditEventIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/contacts/edit/$contactId': {
      id: '/dashboard/contacts/edit/$contactId'
      path: '/contacts/edit/$contactId'
      fullPath: '/dashboard/contacts/edit/$contactId'
      preLoaderRoute: typeof DashboardContactsEditContactIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/contacts/form/item/$submissionId': {
      id: '/dashboard/contacts/form/item/$submissionId'
      path: '/contacts/form/item/$submissionId'
      fullPath: '/dashboard/contacts/form/item/$submissionId'
      preLoaderRoute: typeof DashboardContactsFormItemSubmissionIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardIndexLazyRoute: typeof DashboardIndexLazyRoute
  DashboardSalesAddRoute: typeof DashboardSalesAddRoute
  DashboardContactsAddLazyRoute: typeof DashboardContactsAddLazyRoute
  DashboardEventsAddLazyRoute: typeof DashboardEventsAddLazyRoute
  DashboardMarketsAddLazyRoute: typeof DashboardMarketsAddLazyRoute
  DashboardProductsAddLazyRoute: typeof DashboardProductsAddLazyRoute
  DashboardAnalyticsIndexLazyRoute: typeof DashboardAnalyticsIndexLazyRoute
  DashboardContactsIndexLazyRoute: typeof DashboardContactsIndexLazyRoute
  DashboardEventsIndexLazyRoute: typeof DashboardEventsIndexLazyRoute
  DashboardMarketsIndexLazyRoute: typeof DashboardMarketsIndexLazyRoute
  DashboardNewsletterIndexLazyRoute: typeof DashboardNewsletterIndexLazyRoute
  DashboardProductsIndexLazyRoute: typeof DashboardProductsIndexLazyRoute
  DashboardSalesIndexLazyRoute: typeof DashboardSalesIndexLazyRoute
  DashboardContactsEditContactIdRoute: typeof DashboardContactsEditContactIdRoute
  DashboardEventsEditEventIdRoute: typeof DashboardEventsEditEventIdRoute
  DashboardEventsItemEventIdRoute: typeof DashboardEventsItemEventIdRoute
  DashboardMarketsEditMarketIdRoute: typeof DashboardMarketsEditMarketIdRoute
  DashboardProductsEditProductIdRoute: typeof DashboardProductsEditProductIdRoute
  DashboardProductsItemProductIdRoute: typeof DashboardProductsItemProductIdRoute
  DashboardSalesEditSaleIdRoute: typeof DashboardSalesEditSaleIdRoute
  DashboardAnalyticsTrafficIndexLazyRoute: typeof DashboardAnalyticsTrafficIndexLazyRoute
  DashboardContactsFormIndexLazyRoute: typeof DashboardContactsFormIndexLazyRoute
  DashboardProductsSettingsIndexLazyRoute: typeof DashboardProductsSettingsIndexLazyRoute
  DashboardContactsFormItemSubmissionIdRoute: typeof DashboardContactsFormItemSubmissionIdRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardIndexLazyRoute: DashboardIndexLazyRoute,
  DashboardSalesAddRoute: DashboardSalesAddRoute,
  DashboardContactsAddLazyRoute: DashboardContactsAddLazyRoute,
  DashboardEventsAddLazyRoute: DashboardEventsAddLazyRoute,
  DashboardMarketsAddLazyRoute: DashboardMarketsAddLazyRoute,
  DashboardProductsAddLazyRoute: DashboardProductsAddLazyRoute,
  DashboardAnalyticsIndexLazyRoute: DashboardAnalyticsIndexLazyRoute,
  DashboardContactsIndexLazyRoute: DashboardContactsIndexLazyRoute,
  DashboardEventsIndexLazyRoute: DashboardEventsIndexLazyRoute,
  DashboardMarketsIndexLazyRoute: DashboardMarketsIndexLazyRoute,
  DashboardNewsletterIndexLazyRoute: DashboardNewsletterIndexLazyRoute,
  DashboardProductsIndexLazyRoute: DashboardProductsIndexLazyRoute,
  DashboardSalesIndexLazyRoute: DashboardSalesIndexLazyRoute,
  DashboardContactsEditContactIdRoute: DashboardContactsEditContactIdRoute,
  DashboardEventsEditEventIdRoute: DashboardEventsEditEventIdRoute,
  DashboardEventsItemEventIdRoute: DashboardEventsItemEventIdRoute,
  DashboardMarketsEditMarketIdRoute: DashboardMarketsEditMarketIdRoute,
  DashboardProductsEditProductIdRoute: DashboardProductsEditProductIdRoute,
  DashboardProductsItemProductIdRoute: DashboardProductsItemProductIdRoute,
  DashboardSalesEditSaleIdRoute: DashboardSalesEditSaleIdRoute,
  DashboardAnalyticsTrafficIndexLazyRoute:
    DashboardAnalyticsTrafficIndexLazyRoute,
  DashboardContactsFormIndexLazyRoute: DashboardContactsFormIndexLazyRoute,
  DashboardProductsSettingsIndexLazyRoute:
    DashboardProductsSettingsIndexLazyRoute,
  DashboardContactsFormItemSubmissionIdRoute:
    DashboardContactsFormItemSubmissionIdRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  LoginLazyRoute: LoginLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
