# apps/admin/netlify.toml
[build]
  # This command is run from the monorepo root.
  command = "bun run build --filter=...admin"

  publish = "apps/admin/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200